spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 2
          max-interval: 1s
          multiplier: 2
  datasource:
    url: jdbc:mysql://led-strip.cdchq3xrzcox.us-east-1.rds.amazonaws.com:3306/klinc
    username: klinc-backend
    password: Be51k0siYE3V
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'false'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'false'
messaging:
  subscription:
    update-subscription: update-subscription
  user:
    user-created: user-created
